"""
Master Enums and Constants for FlexiTaka.
Adheres strictly to FlexiTaka Backend Development Master Specification.
"""

from enum import Enum
from decimal import Decimal, ROUND_HALF_UP


class ServiceType(str, Enum):
    CASH_OUT = "CASH_OUT"
    RECHARGE = "RECHARGE"


class CashOutStatus(str, Enum):
    REQUESTED = "REQUESTED"
    WAITING_FOR_TRANSFER = "WAITING_FOR_TRANSFER"
    TRANSFER_IN_PROGRESS = "TRANSFER_IN_PROGRESS"
    PARTIALLY_COMPLETED = "PARTIALLY_COMPLETED"
    TRANSFER_RECEIVED = "TRANSFER_RECEIVED"
    TRANSFER_FAILED = "TRANSFER_FAILED"
    INSUFFICIENT_BALANCE = "INSUFFICIENT_BALANCE"
    UNDER_VERIFICATION = "UNDER_VERIFICATION"
    APPROVED = "APPROVED"
    PAYOUT_PROCESSING = "PAYOUT_PROCESSING"
    COMPLETED = "COMPLETED"
    REJECTED = "REJECTED"
    CANCELLED = "CANCELLED"


class TransferAuthMode(str, Enum):
    SESSION_PLUS_PIN = "SESSION_PLUS_PIN"
    OTP_PER_TRANSFER = "OTP_PER_TRANSFER"
    OTP_FOR_PIN_SETUP_ONLY = "OTP_FOR_PIN_SETUP_ONLY"
    OPERATOR_SPECIFIC = "OPERATOR_SPECIFIC"


class QuotaWindowType(str, Enum):
    CALENDAR_MONTH = "CALENDAR_MONTH"
    ROLLING_30_DAYS = "ROLLING_30_DAYS"
    DAILY = "DAILY"


class RechargeStatus(str, Enum):
    REQUESTED = "REQUESTED"
    PAYMENT_PENDING = "PAYMENT_PENDING"
    PAYMENT_VERIFIED = "PAYMENT_VERIFIED"
    RECHARGE_PROCESSING = "RECHARGE_PROCESSING"
    COMPLETED = "COMPLETED"
    PAYMENT_FAILED = "PAYMENT_FAILED"
    REJECTED = "REJECTED"
    CANCELLED = "CANCELLED"


class PayoutStatus(str, Enum):
    PENDING = "PENDING"
    PROCESSING = "PROCESSING"
    SENT = "SENT"
    FAILED = "FAILED"
    CANCELLED = "CANCELLED"


class PaymentStatus(str, Enum):
    PENDING = "PENDING"
    VERIFIED = "VERIFIED"
    FAILED = "FAILED"
    CANCELLED = "CANCELLED"


class SupportStatus(str, Enum):
    OPEN = "OPEN"
    IN_PROGRESS = "IN_PROGRESS"
    WAITING_FOR_USER = "WAITING_FOR_USER"
    RESOLVED = "RESOLVED"
    CLOSED = "CLOSED"


class AdminRole(str, Enum):
    SUPER_ADMIN = "SUPER_ADMIN"
    ADMIN = "ADMIN"
    SUPPORT = "SUPPORT"
    FINANCE = "FINANCE"
    VERIFIER = "VERIFIER"
    OPERATIONS = "OPERATIONS"


class OperatorCode(str, Enum):
    GP = "GP"
    ROBI = "ROBI"
    BANGLALINK = "BANGLALINK"


class PayoutMethod(str, Enum):
    BKASH = "BKASH"
    NAGAD = "NAGAD"
    BANK = "BANK"


class SimStatus(str, Enum):
    ACTIVE = "ACTIVE"
    INACTIVE = "INACTIVE"
    BLOCKED = "BLOCKED"
    MAINTENANCE = "MAINTENANCE"


class InventoryMovementType(str, Enum):
    TRANSFER_RECEIVED = "TRANSFER_RECEIVED"
    RECHARGE_CONSUMED = "RECHARGE_CONSUMED"
    MANUAL_ADJUSTMENT = "MANUAL_ADJUSTMENT"
    REVERSAL = "REVERSAL"
    CORRECTION = "CORRECTION"


class ActorType(str, Enum):
    SYSTEM = "SYSTEM"
    USER = "USER"
    GUEST = "GUEST"
    STAFF = "STAFF"


class ErrorCode(str, Enum):
    AUTH_REQUIRED = "AUTH_REQUIRED"
    INVALID_OTP = "INVALID_OTP"
    INVALID_MOBILE_NUMBER = "INVALID_MOBILE_NUMBER"
    INVALID_OPERATOR = "INVALID_OPERATOR"
    INVALID_AMOUNT = "INVALID_AMOUNT"
    AMOUNT_OUT_OF_RANGE = "AMOUNT_OUT_OF_RANGE"
    OTP_REQUIRED = "OTP_REQUIRED"
    SERVICE_UNAVAILABLE = "SERVICE_UNAVAILABLE"
    ORDER_NOT_FOUND = "ORDER_NOT_FOUND"
    INVALID_ORDER_STATUS = "INVALID_ORDER_STATUS"
    PROOF_REQUIRED = "PROOF_REQUIRED"
    PROOF_INVALID = "PROOF_INVALID"
    PAYMENT_REQUIRED = "PAYMENT_REQUIRED"
    PAYMENT_FAILED = "PAYMENT_FAILED"
    PAYOUT_FAILED = "PAYOUT_FAILED"
    PAYOUT_ALREADY_EXISTS = "PAYOUT_ALREADY_EXISTS"
    DUPLICATE_REQUEST = "DUPLICATE_REQUEST"
    IDEMPOTENCY_CONFLICT = "IDEMPOTENCY_CONFLICT"
    PERMISSION_DENIED = "PERMISSION_DENIED"
    RATE_LIMITED = "RATE_LIMITED"
    FILE_TOO_LARGE = "FILE_TOO_LARGE"
    FILE_TYPE_NOT_ALLOWED = "FILE_TYPE_NOT_ALLOWED"
    RECEIVING_SIM_UNAVAILABLE = "RECEIVING_SIM_UNAVAILABLE"
    RECEIVING_SIM_OPERATOR_MISMATCH = "RECEIVING_SIM_OPERATOR_MISMATCH"
    OPERATOR_NUMBER_MISMATCH = "OPERATOR_NUMBER_MISMATCH"
    UNSUPPORTED_OPERATOR_PREFIX = "UNSUPPORTED_OPERATOR_PREFIX"
    INSUFFICIENT_BALANCE = "INSUFFICIENT_BALANCE"
    TRANSFER_FAILED = "TRANSFER_FAILED"
    INVALID_PAYOUT_METHOD = "INVALID_PAYOUT_METHOD"
    SESSION_EXPIRED = "SESSION_EXPIRED"
    OTP_INVALID = "OTP_INVALID"
    OTP_EXPIRED = "OTP_EXPIRED"
    PIN_INVALID = "PIN_INVALID"
    PIN_RESET_REQUIRED = "PIN_RESET_REQUIRED"
    TRANSFER_LIMIT_REACHED = "TRANSFER_LIMIT_REACHED"
    TRANSFER_COUNT_LIMIT_REACHED = "TRANSFER_COUNT_LIMIT_REACHED"
    DAILY_QUOTA_EXCEEDED = "DAILY_QUOTA_EXCEEDED"
    MONTHLY_QUOTA_EXCEEDED = "MONTHLY_QUOTA_EXCEEDED"
    COOLDOWN_ACTIVE = "COOLDOWN_ACTIVE"
    DESTINATION_INVALID = "DESTINATION_INVALID"
    OPERATOR_MISMATCH = "OPERATOR_MISMATCH"
    TEMPORARY_OPERATOR_ERROR = "TEMPORARY_OPERATOR_ERROR"
    AMBIGUOUS_TRANSFER = "AMBIGUOUS_TRANSFER"
    VALIDATION_ERROR = "VALIDATION_ERROR"
    INTERNAL_SERVER_ERROR = "INTERNAL_SERVER_ERROR"


# Business Amount Limits (10 to 50,000 BDT)
MIN_ORDER_AMOUNT_BDT = 10
MAX_ORDER_AMOUNT_BDT = 50000
MIN_ORDER_AMOUNT_POISHA = 1000
MAX_ORDER_AMOUNT_POISHA = 5000000


# Allowed state transitions for Cash Out
CASHOUT_ALLOWED_TRANSITIONS = {
    CashOutStatus.REQUESTED: {CashOutStatus.WAITING_FOR_TRANSFER, CashOutStatus.TRANSFER_IN_PROGRESS, CashOutStatus.CANCELLED},
    CashOutStatus.WAITING_FOR_TRANSFER: {CashOutStatus.TRANSFER_IN_PROGRESS, CashOutStatus.PARTIALLY_COMPLETED, CashOutStatus.TRANSFER_RECEIVED, CashOutStatus.UNDER_VERIFICATION, CashOutStatus.CANCELLED},
    CashOutStatus.TRANSFER_IN_PROGRESS: {CashOutStatus.PARTIALLY_COMPLETED, CashOutStatus.TRANSFER_RECEIVED, CashOutStatus.TRANSFER_FAILED, CashOutStatus.INSUFFICIENT_BALANCE, CashOutStatus.UNDER_VERIFICATION, CashOutStatus.CANCELLED},
    CashOutStatus.PARTIALLY_COMPLETED: {CashOutStatus.TRANSFER_IN_PROGRESS, CashOutStatus.TRANSFER_RECEIVED, CashOutStatus.TRANSFER_FAILED, CashOutStatus.UNDER_VERIFICATION, CashOutStatus.CANCELLED},
    CashOutStatus.TRANSFER_RECEIVED: {CashOutStatus.UNDER_VERIFICATION, CashOutStatus.APPROVED, CashOutStatus.CANCELLED},
    CashOutStatus.TRANSFER_FAILED: {CashOutStatus.WAITING_FOR_TRANSFER, CashOutStatus.PARTIALLY_COMPLETED, CashOutStatus.CANCELLED},
    CashOutStatus.INSUFFICIENT_BALANCE: {CashOutStatus.WAITING_FOR_TRANSFER, CashOutStatus.PARTIALLY_COMPLETED, CashOutStatus.CANCELLED},
    CashOutStatus.UNDER_VERIFICATION: {CashOutStatus.APPROVED, CashOutStatus.REJECTED, CashOutStatus.CANCELLED},
    CashOutStatus.APPROVED: {CashOutStatus.PAYOUT_PROCESSING, CashOutStatus.CANCELLED},
    CashOutStatus.PAYOUT_PROCESSING: {CashOutStatus.COMPLETED, CashOutStatus.REJECTED},
    CashOutStatus.COMPLETED: set(),  # Terminal
    CashOutStatus.REJECTED: set(),   # Terminal
    CashOutStatus.CANCELLED: set(),  # Terminal
}

# Allowed state transitions for Recharge
RECHARGE_ALLOWED_TRANSITIONS = {
    RechargeStatus.REQUESTED: {RechargeStatus.PAYMENT_PENDING, RechargeStatus.CANCELLED},
    RechargeStatus.PAYMENT_PENDING: {RechargeStatus.PAYMENT_VERIFIED, RechargeStatus.PAYMENT_FAILED, RechargeStatus.CANCELLED},
    RechargeStatus.PAYMENT_VERIFIED: {RechargeStatus.RECHARGE_PROCESSING, RechargeStatus.CANCELLED},
    RechargeStatus.RECHARGE_PROCESSING: {RechargeStatus.COMPLETED, RechargeStatus.REJECTED},
    RechargeStatus.COMPLETED: set(),       # Terminal
    RechargeStatus.PAYMENT_FAILED: set(),  # Terminal
    RechargeStatus.REJECTED: set(),        # Terminal
    RechargeStatus.CANCELLED: set(),       # Terminal
}


def bdt_to_poisha(amount_bdt: Decimal | str | int) -> int:
    """Convert BDT (e.g. 100.50) to integer poisha (10050) using Decimal with standard rounding."""
    dec = Decimal(str(amount_bdt))
    return int((dec * Decimal("100")).quantize(Decimal("1"), rounding=ROUND_HALF_UP))


def poisha_to_bdt(poisha: int) -> Decimal:
    """Convert integer poisha (10050) to Decimal BDT (100.50)."""
    return (Decimal(poisha) / Decimal("100")).quantize(Decimal("0.01"), rounding=ROUND_HALF_UP)
